/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bingbong;

import com.google.api.core.ApiFuture;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.Firestore;

import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.cloud.FirestoreClient;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Map;
import java.util.Scanner;
import java.util.concurrent.ExecutionException;

    class userInfo {
    static String username;
    static String password;
    static float balance;
    static int accn;
    }
public class App {
    public static void main(String[] args) throws IOException, InterruptedException, ExecutionException {
        // Use the application default credentials
FileInputStream serviceAccount =
  new FileInputStream("name.json");

FirebaseOptions options = new FirebaseOptions.Builder()
  .setCredentials(GoogleCredentials.fromStream(serviceAccount))
  .build();
FirebaseApp.initializeApp(options);

Firestore db = FirestoreClient.getFirestore();
DocumentReference userAccounts = db.collection("UserAccounts").document();
ApiFuture<DocumentSnapshot> future = userAccounts.get();
DocumentSnapshot document = future.get();
Map users = document.getData();

//This is where the actual app starts
System.out.println("Welcome to the Bank of Waste.");
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter your username");
        System.out.print("> ");
        String username = scanner.nextLine();
        userInfo.username = username;
        System.out.println("Please enter the password for the account associated with " + userInfo.username);
        System.out.print("> ");
        String password = scanner.nextLine();
        /*if(password != users.username){
            
        }*/
        System.out.println(users);
        System.out.println("Hello " + userInfo.username);
        System.out.println("$" + userInfo.balance);
    }
}